BEGIN;

INSERT INTO official_sources (source_key, metadata, enabled, created_at, updated_at, deleted_at)
VALUES (
  'HAF',
  '{"source_key":"HAF","name":"Hope and Fear","short_title":"H&F"}',
  1,
  unixepoch() * 1000,
  unixepoch() * 1000,
  NULL
)
ON CONFLICT(source_key) DO UPDATE SET
  metadata = excluded.metadata,
  enabled = 1,
  updated_at = unixepoch() * 1000,
  deleted_at = NULL;

CREATE TEMP TABLE _haf_primary_weapons (
  item_type TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item TEXT NOT NULL,
  PRIMARY KEY (item_type, item_id)
);

INSERT INTO _haf_primary_weapons (item_type, item_id, item)
VALUES
('primary_weapons', 'katana', '{"source_key":"HAF","title":"Katana","description_html":"","level_requirement":1,"type":"Physical","available_traits":["agility"],"range":"Melee","features":[{"title":"Quick","description_html":"When you make an attack, you can mark a Stress to target another creature within range.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'brass_knuckles', '{"source_key":"HAF","title":"Brass Knuckles","description_html":"","level_requirement":1,"type":"Physical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":1,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'scimitar', '{"source_key":"HAF","title":"Scimitar","description_html":"","level_requirement":1,"type":"Physical","available_traits":["presence"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":1,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'twisted_dagger', '{"source_key":"HAF","title":"Twisted Dagger","description_html":"","level_requirement":1,"type":"Physical","available_traits":["knowledge"],"range":"Melee","features":[{"title":"Piercing","description_html":"Damage dealt with this weapon treats the target''s Major threshold as having a -2 penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":0,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'whipsword', '{"source_key":"HAF","title":"Whipsword","description_html":"","level_requirement":1,"type":"Physical","available_traits":["finesse"],"range":"Very Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Finesse, Melee, d10.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":0,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'rope_dart', '{"source_key":"HAF","title":"Rope Dart","description_html":"","level_requirement":1,"type":"Physical","available_traits":["instinct"],"range":"Close","features":[],"attack_roll_bonus":0,"damage_bonus":1,"damage_dice":"1d6","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'brightsword', '{"source_key":"HAF","title":"Brightsword","description_html":"","level_requirement":1,"type":"Magical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'shadowblade', '{"source_key":"HAF","title":"Shadowblade","description_html":"","level_requirement":1,"type":"Magical","available_traits":["presence"],"range":"Melee","features":[{"title":"Otherworldly","description_html":"On a successful attack, you can deal physical or magic damage.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":0,"damage_dice":"1d8","available_damage_types":["phy","mag"],"burden":1}'),
('primary_weapons', 'enchanted_chakram', '{"source_key":"HAF","title":"Enchanted Chakram","description_html":"","level_requirement":1,"type":"Magical","available_traits":["finesse"],"range":"Close","features":[{"title":"Ricochet","description_html":"When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":1,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'casting_dagger', '{"source_key":"HAF","title":"Casting Dagger","description_html":"","level_requirement":1,"type":"Magical","available_traits":["instinct"],"range":"Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Instinct, Melee, d8.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":0,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'runelock_pistol', '{"source_key":"HAF","title":"Runelock Pistol","description_html":"","level_requirement":1,"type":"Magical","available_traits":["knowledge"],"range":"Far","features":[{"title":"Reloading","description_html":"After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'arcane_rifle', '{"source_key":"HAF","title":"Arcane Rifle","description_html":"","level_requirement":1,"type":"Magical","available_traits":["agility"],"range":"Very Far","features":[{"title":"Aimed","description_html":"Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'improved_katana', '{"source_key":"HAF","title":"Improved Katana","description_html":"","level_requirement":2,"type":"Physical","available_traits":["agility"],"range":"Melee","features":[{"title":"Quick","description_html":"When you make an attack, you can mark a Stress to target another creature within range.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'improved_brass_knuckles', '{"source_key":"HAF","title":"Improved Brass Knuckles","description_html":"","level_requirement":2,"type":"Physical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":4,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'improved_scimitar', '{"source_key":"HAF","title":"Improved Scimitar","description_html":"","level_requirement":2,"type":"Physical","available_traits":["presence"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":4,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'improved_twisted_dagger', '{"source_key":"HAF","title":"Improved Twisted Dagger","description_html":"","level_requirement":2,"type":"Physical","available_traits":["knowledge"],"range":"Melee","features":[{"title":"Piercing","description_html":"Damage dealt with this weapon treats the target''s Major threshold as having a -2 penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'improved_whipsword', '{"source_key":"HAF","title":"Improved Whipsword","description_html":"","level_requirement":2,"type":"Physical","available_traits":["finesse"],"range":"Very Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Finesse, Melee, d10+3.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'improved_rope_dart', '{"source_key":"HAF","title":"Improved Rope Dart","description_html":"","level_requirement":2,"type":"Physical","available_traits":["instinct"],"range":"Close","features":[],"attack_roll_bonus":0,"damage_bonus":4,"damage_dice":"1d6","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'war_pick', '{"source_key":"HAF","title":"War Pick","description_html":"","level_requirement":2,"type":"Physical","available_traits":["strength"],"range":"Melee","features":[{"title":"Deadly","description_html":"When you deal Severe damage, the target must mark an additional HP.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'cane_sword', '{"source_key":"HAF","title":"Cane Sword","description_html":"","level_requirement":2,"type":"Physical","available_traits":["finesse"],"range":"Melee","features":[{"title":"Retractable","description_html":"The blade can be hidden in the cane to avoid detection.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":4,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'bladed_fan', '{"source_key":"HAF","title":"Bladed Fan","description_html":"","level_requirement":2,"type":"Physical","available_traits":["presence"],"range":"Melee","features":[{"title":"Parry","description_html":"When you are attacked, roll this weapon''s damage dice. If any of the attacker''s damage dice rolled the same value as your dice, the matching results are discarded from the attacker''s damage dice before the damage you take is totaled.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'cyrurgiens_scalpel', '{"source_key":"HAF","title":"Cyrurgien''s Scalpel","description_html":"","level_requirement":2,"type":"Physical","available_traits":["knowledge"],"range":"Melee","features":[{"title":"Scary","description_html":"On a successful attack, the target must mark a Stress.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'lance', '{"source_key":"HAF","title":"Lance","description_html":"","level_requirement":2,"type":"Physical","available_traits":["instinct"],"range":"Very Close","features":[{"title":"Cumbersome","description_html":"-1 to Finesse","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":5,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'javelins', '{"source_key":"HAF","title":"Javelins","description_html":"","level_requirement":2,"type":"Physical","available_traits":["agility"],"range":"Very Close","features":[{"title":"Stockpiled","description_html":"You can throw this weapon at a target within Far range by making an attack roll using Agility without having to retrieve it, as you always have another one on hand.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d6","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'improved_brightsword', '{"source_key":"HAF","title":"Improved Brightsword","description_html":"","level_requirement":2,"type":"Magical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'improved_shadowblade', '{"source_key":"HAF","title":"Improved Shadowblade","description_html":"","level_requirement":2,"type":"Magical","available_traits":["presence"],"range":"Melee","features":[{"title":"Otherworldly","description_html":"On a successful attack, you can deal physical or magic damage.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["phy","mag"],"burden":1}'),
('primary_weapons', 'improved_enchanted_chakram', '{"source_key":"HAF","title":"Improved Enchanted Chakram","description_html":"","level_requirement":2,"type":"Magical","available_traits":["finesse"],"range":"Close","features":[{"title":"Ricochet","description_html":"When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":4,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'improved_casting_dagger', '{"source_key":"HAF","title":"Improved Casting Dagger","description_html":"","level_requirement":2,"type":"Magical","available_traits":["instinct"],"range":"Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Instinct, Melee, d8+3.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'improved_runelock_pistol', '{"source_key":"HAF","title":"Improved Runelock Pistol","description_html":"","level_requirement":2,"type":"Magical","available_traits":["knowledge"],"range":"Far","features":[{"title":"Reloading","description_html":"After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'improved_arcane_rifle', '{"source_key":"HAF","title":"Improved Arcane Rifle","description_html":"","level_requirement":2,"type":"Magical","available_traits":["agility"],"range":"Very Far","features":[{"title":"Aimed","description_html":"Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'enchanted_shillelagh', '{"source_key":"HAF","title":"Enchanted Shillelagh","description_html":"","level_requirement":2,"type":"Magical","available_traits":["strength"],"range":"Melee","features":[{"title":"Protective","description_html":"+1 to your Armor Score","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'displacement_razor', '{"source_key":"HAF","title":"Displacement Razor","description_html":"","level_requirement":2,"type":"Magical","available_traits":["finesse"],"range":"Melee","features":[{"title":"Omnipresent","description_html":"You can make attacks against targets within Very Far range, but must do so with disadvantage.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'spellbound_bangles', '{"source_key":"HAF","title":"Spellbound Bangles","description_html":"","level_requirement":2,"type":"Magical","available_traits":["knowledge"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'fury_gem', '{"source_key":"HAF","title":"Fury Gem","description_html":"","level_requirement":2,"type":"Magical","available_traits":["instinct"],"range":"Close","features":[{"title":"Burning","description_html":"When you roll the maximum result on a damage die, the target must mark a Stress.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'enchanted_lute', '{"source_key":"HAF","title":"Enchanted Lute","description_html":"","level_requirement":2,"type":"Magical","available_traits":["presence"],"range":"Close","features":[{"title":"Invigorating","description_html":"On a successful attack, roll a d4. On a result of 4, clear a Stress.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":3,"damage_dice":"1d8","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'splintershaft_bow', '{"source_key":"HAF","title":"Splintershaft Bow","description_html":"","level_requirement":2,"type":"Magical","available_traits":["agility"],"range":"Far","features":[{"title":"Volleyed","description_html":"Spend a Hope to target a group of creatures within range. Targets you succeed against take half damage.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d6","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'advanced_katana', '{"source_key":"HAF","title":"Advanced Katana","description_html":"","level_requirement":5,"type":"Physical","available_traits":["agility"],"range":"Melee","features":[{"title":"Quick","description_html":"When you make an attack, you can mark a Stress to target another creature within range.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'advanced_brass_knuckles', '{"source_key":"HAF","title":"Advanced Brass Knuckles","description_html":"","level_requirement":5,"type":"Physical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'advanced_scimitar', '{"source_key":"HAF","title":"Advanced Scimitar","description_html":"","level_requirement":5,"type":"Physical","available_traits":["presence"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'advanced_twisted_dagger', '{"source_key":"HAF","title":"Advanced Twisted Dagger","description_html":"","level_requirement":5,"type":"Physical","available_traits":["knowledge"],"range":"Melee","features":[{"title":"Piercing","description_html":"Damage dealt with this weapon treats the target''s Major threshold as having a -2 penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'advanced_whipsword', '{"source_key":"HAF","title":"Advanced Whipsword","description_html":"","level_requirement":5,"type":"Physical","available_traits":["finesse"],"range":"Very Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Finesse, Melee, d10+6.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'advanced_rope_dart', '{"source_key":"HAF","title":"Advanced Rope Dart","description_html":"","level_requirement":5,"type":"Physical","available_traits":["instinct"],"range":"Close","features":[],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d6","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'blitz_hammer', '{"source_key":"HAF","title":"Blitz Hammer","description_html":"","level_requirement":5,"type":"Physical","available_traits":["strength"],"range":"Melee","features":[{"title":"Accelerator","description_html":"Once per scene, mark a Stress to move to Far range then make an attack. Gain a +1 bonus to your Proficiency on this attack.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'platinum_estoc', '{"source_key":"HAF","title":"Platinum Estoc","description_html":"","level_requirement":5,"type":"Physical","available_traits":["finesse"],"range":"Melee","features":[{"title":"Piercing","description_html":"Damage dealt with this weapon treats the target''s Major threshold as having a -2 penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'soldier_s_pike', '{"source_key":"HAF","title":"Soldier''s Pike","description_html":"","level_requirement":5,"type":"Physical","available_traits":["agility"],"range":"Very Close","features":[{"title":"Braced","description_html":"When an adversary within this weapon''s range deals damage to you, you can mark 2 Stress to force them to mark a Hit Point.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":5,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'chained_scythe', '{"source_key":"HAF","title":"Chained Scythe","description_html":"","level_requirement":5,"type":"Physical","available_traits":["instinct"],"range":"Very Close","features":[{"title":"Quick","description_html":"When you make an attack, you can mark a Stress to target another creature within range.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":5,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'singing_sword', '{"source_key":"HAF","title":"Singing Sword","description_html":"","level_requirement":5,"type":"Physical","available_traits":["presence"],"range":"Very Close","features":[{"title":"Bolstering","description_html":"When you critically succeed on an attack, all PCs within Close range gain a Hope.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":5,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'bladed_star', '{"source_key":"HAF","title":"Bladed Star","description_html":"","level_requirement":5,"type":"Physical","available_traits":["knowledge"],"range":"Close","features":[{"title":"Rebounding","description_html":"When you throw this weapon, it returns to your hand. On a failed attack, you can reroll your attack with disadvantage.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'advanced_brightsword', '{"source_key":"HAF","title":"Advanced Brightsword","description_html":"","level_requirement":5,"type":"Magical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'advanced_shadowblade', '{"source_key":"HAF","title":"Advanced Shadowblade","description_html":"","level_requirement":5,"type":"Magical","available_traits":["presence"],"range":"Melee","features":[{"title":"Otherworldly","description_html":"On a successful attack, you can deal physical or magic damage.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d8","available_damage_types":["phy","mag"],"burden":1}'),
('primary_weapons', 'advanced_enchanted_chakram', '{"source_key":"HAF","title":"Advanced Enchanted Chakram","description_html":"","level_requirement":5,"type":"Magical","available_traits":["finesse"],"range":"Close","features":[{"title":"Ricochet","description_html":"When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'advanced_casting_dagger', '{"source_key":"HAF","title":"Advanced Casting Dagger","description_html":"","level_requirement":5,"type":"Magical","available_traits":["instinct"],"range":"Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Instinct, Melee, d8+6.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'advanced_runelock_pistol', '{"source_key":"HAF","title":"Advanced Runelock Pistol","description_html":"","level_requirement":5,"type":"Magical","available_traits":["knowledge"],"range":"Far","features":[{"title":"Reloading","description_html":"After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'advanced_arcane_rifle', '{"source_key":"HAF","title":"Advanced Arcane Rifle","description_html":"","level_requirement":5,"type":"Magical","available_traits":["agility"],"range":"Very Far","features":[{"title":"Aimed","description_html":"Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'rocket_maul', '{"source_key":"HAF","title":"Rocket Maul","description_html":"","level_requirement":5,"type":"Magical","available_traits":["strength"],"range":"Melee","features":[{"title":"Concussive","description_html":"On a successful attack, you can spend a Hope to knock the target back to Far range.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'crystal_spear', '{"source_key":"HAF","title":"Crystal Spear","description_html":"","level_requirement":5,"type":"Magical","available_traits":["finesse"],"range":"Very Close","features":[{"title":"Piercing","description_html":"Damage dealt with this weapon treats the target''s Major threshold as having a -2 penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d10","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'arc_wand', '{"source_key":"HAF","title":"Arc Wand","description_html":"","level_requirement":5,"type":"Magical","available_traits":["presence"],"range":"Close","features":[{"title":"Bouncing","description_html":"Mark any number of Stress to target that many additional creatures in range of the attack.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d8","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'rime_scepter', '{"source_key":"HAF","title":"Rime Scepter","description_html":"","level_requirement":5,"type":"Magical","available_traits":["knowledge"],"range":"Close","features":[{"title":"Freezing","description_html":"When an attack from this weapon causes a target to mark 2 or more HP, they become temporarily Restrained.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d8","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'gunblade', '{"source_key":"HAF","title":"Gunblade","description_html":"","level_requirement":5,"type":"Magical","available_traits":["agility"],"range":"Far","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Agility, Melee, d8+6 phy.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'staff_of_augma', '{"source_key":"HAF","title":"Staff of Augma","description_html":"","level_requirement":5,"type":"Magical","available_traits":["instinct"],"range":"Far","features":[{"title":"Catalytic","description_html":"On a successful attack, you can mark a Stress to give an ally within Close range a +3 bonus to their next attack roll.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":7,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'legendary_katana', '{"source_key":"HAF","title":"Legendary Katana","description_html":"","level_requirement":8,"type":"Physical","available_traits":["agility"],"range":"Melee","features":[{"title":"Quick","description_html":"When you make an attack, you can mark a Stress to target another creature within range.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":12,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'legendary_brass_knuckles', '{"source_key":"HAF","title":"Legendary Brass Knuckles","description_html":"","level_requirement":8,"type":"Physical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":10,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'legendary_scimitar', '{"source_key":"HAF","title":"Legendary Scimitar","description_html":"","level_requirement":8,"type":"Physical","available_traits":["presence"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":10,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'legendary_twisted_dagger', '{"source_key":"HAF","title":"Legendary Twisted Dagger","description_html":"","level_requirement":8,"type":"Physical","available_traits":["knowledge"],"range":"Melee","features":[{"title":"Piercing","description_html":"Damage dealt with this weapon treats the target''s Major threshold as having a -2 penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'legendary_whipsword', '{"source_key":"HAF","title":"Legendary Whipsword","description_html":"","level_requirement":8,"type":"Physical","available_traits":["finesse"],"range":"Very Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Finesse, Melee, d10+9.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d8","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'legendary_rope_dart', '{"source_key":"HAF","title":"Legendary Rope Dart","description_html":"","level_requirement":8,"type":"Physical","available_traits":["instinct"],"range":"Close","features":[],"attack_roll_bonus":0,"damage_bonus":10,"damage_dice":"1d6","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'severed_dragon_claw', '{"source_key":"HAF","title":"Severed Dragon Claw","description_html":"","level_requirement":8,"type":"Physical","available_traits":["instinct"],"range":"Melee","features":[{"title":"Destructive","description_html":"-1 to Agility; on a successful attack, all adversaries within Very Close range must mark a Stress.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":11,"damage_dice":"1d10","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'infinite_staff', '{"source_key":"HAF","title":"Infinite Staff","description_html":"","level_requirement":8,"type":"Physical","available_traits":["presence"],"range":"Melee","features":[{"title":"Extending","description_html":"You can increase the range of this weapon up to Very Far. You gain a -1 penalty to attack rolls for each step you increase the range by (such as Melee to Very Close, Very Close to Close, or Close to Far).","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'bec_de_corbin', '{"source_key":"HAF","title":"Bec de Corbin","description_html":"","level_requirement":8,"type":"Physical","available_traits":["agility"],"range":"Very Close","features":[{"title":"Devastating","description_html":"Before you make an attack roll, you can mark a Stress to use a d20 as your damage die.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d10","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'black_powder_serpentine', '{"source_key":"HAF","title":"Black Powder Serpentine","description_html":"","level_requirement":8,"type":"Physical","available_traits":["strength"],"range":"Far","features":[{"title":"Incendiary","description_html":"-1 to Agility; on a successful attack, all creatures within Very Close range of the target must mark a Hit Point.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":12,"damage_dice":"1d8","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'clockwork_crossbow', '{"source_key":"HAF","title":"Clockwork Crossbow","description_html":"","level_requirement":8,"type":"Physical","available_traits":["finesse"],"range":"Far","features":[{"title":"Quick","description_html":"When you make an attack, you can mark a Stress to target another creature within range.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":11,"damage_dice":"1d6","available_damage_types":["phy"],"burden":1}'),
('primary_weapons', 'arquebus', '{"source_key":"HAF","title":"Arquebus","description_html":"","level_requirement":8,"type":"Physical","available_traits":["knowledge"],"range":"Far","features":[{"title":"Reloading","description_html":"After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":10,"damage_dice":"1d8","available_damage_types":["phy"],"burden":2}'),
('primary_weapons', 'legendary_brightsword', '{"source_key":"HAF","title":"Legendary Brightsword","description_html":"","level_requirement":8,"type":"Magical","available_traits":["strength"],"range":"Melee","features":[],"attack_roll_bonus":0,"damage_bonus":12,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'legendary_shadowblade', '{"source_key":"HAF","title":"Legendary Shadowblade","description_html":"","level_requirement":8,"type":"Magical","available_traits":["presence"],"range":"Melee","features":[{"title":"Otherworldly","description_html":"On a successful attack, you can deal physical or magic damage.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d8","available_damage_types":["phy","mag"],"burden":1}'),
('primary_weapons', 'legendary_enchanted_chakram', '{"source_key":"HAF","title":"Legendary Enchanted Chakram","description_html":"","level_requirement":8,"type":"Magical","available_traits":["finesse"],"range":"Close","features":[{"title":"Ricochet","description_html":"When you throw this weapon, it returns to your hand. When you make an attack, you can mark a Stress to target another creature within Very Close range of the first target with that attack.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":10,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'legendary_casting_dagger', '{"source_key":"HAF","title":"Legendary Casting Dagger","description_html":"","level_requirement":8,"type":"Magical","available_traits":["instinct"],"range":"Close","features":[{"title":"Versatile","description_html":"This weapon can also be used with these statistics--Instinct, Melee, d8+9.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'legendary_runelock_pistol', '{"source_key":"HAF","title":"Legendary Runelock Pistol","description_html":"","level_requirement":8,"type":"Magical","available_traits":["knowledge"],"range":"Far","features":[{"title":"Reloading","description_html":"After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":12,"damage_dice":"1d6","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'legendary_arcane_rifle', '{"source_key":"HAF","title":"Legendary Arcane Rifle","description_html":"","level_requirement":8,"type":"Magical","available_traits":["agility"],"range":"Very Far","features":[{"title":"Aimed","description_html":"Your attack has disadvantage if the target is within Very Close range of you or within Melee range of one of your allies. You can mark a Stress to ignore this penalty.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":12,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'starmetal_blade', '{"source_key":"HAF","title":"Starmetal Blade","description_html":"","level_requirement":8,"type":"Magical","available_traits":["agility"],"range":"Melee","features":[{"title":"Serrated","description_html":"When you roll a 1 on a damage die, it deals 8 damage instead.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":10,"damage_dice":"1d8","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'adder_s_fang', '{"source_key":"HAF","title":"Adder''s Fang","description_html":"","level_requirement":8,"type":"Magical","available_traits":["finesse"],"range":"Melee","features":[{"title":"Venomous","description_html":"When you deal Major or greater damage with this weapon, the target becomes temporarily Vulnerable.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d8","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'demon_s_edge', '{"source_key":"HAF","title":"Demon''s Edge","description_html":"","level_requirement":8,"type":"Magical","available_traits":["presence"],"range":"Melee","features":[{"title":"Disturbing","description_html":"When you defeat a creature with this weapon, all adversaries within Close range must mark a Stress.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":10,"damage_dice":"1d8","available_damage_types":["mag"],"burden":1}'),
('primary_weapons', 'storm_god_s_greataxe', '{"source_key":"HAF","title":"Storm God''s Greataxe","description_html":"","level_requirement":8,"type":"Magical","available_traits":["strength"],"range":"Very Close","features":[{"title":"Bouncing","description_html":"Mark any number of Stress to target that many additional creatures in range of the attack.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'ethereal_zweihander', '{"source_key":"HAF","title":"Ethereal Zweihander","description_html":"","level_requirement":8,"type":"Magical","available_traits":["instinct"],"range":"Very Close","features":[{"title":"Ethereal","description_html":"You must mark a Stress to conjure this weapon. It lasts until the end of the scene.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":9,"damage_dice":"1d10","available_damage_types":["mag"],"burden":2}'),
('primary_weapons', 'gravity_arbalest', '{"source_key":"HAF","title":"Gravity Arbalest","description_html":"","level_requirement":8,"type":"Magical","available_traits":["knowledge"],"range":"Far","features":[{"title":"Magnetic","description_html":"When you make an attack with this weapon, you can spend a Hope to force all adversaries within Very Close range of the target to make a Reaction Roll (16). Creatures who fail must mark a Stress and are pulled into Melee range of the target.","character_modifiers":[],"weapon_modifiers":[]}],"attack_roll_bonus":0,"damage_bonus":6,"damage_dice":"1d8","available_damage_types":["mag"],"burden":2}');

INSERT INTO official_compendium_items (
  item_type,
  item_id,
  source_key,
  current_version,
  created_at,
  updated_at,
  deleted_at
)
SELECT
  item_type,
  item_id,
  'HAF',
  1,
  unixepoch() * 1000,
  unixepoch() * 1000,
  NULL
FROM _haf_primary_weapons
WHERE true
ON CONFLICT(source_key, item_type, item_id) DO UPDATE SET
  current_version = 1,
  updated_at = unixepoch() * 1000,
  deleted_at = NULL;

INSERT INTO official_compendium_item_versions (
  item_type,
  item_id,
  source_key,
  item_version,
  label,
  changelog,
  item,
  created_at,
  published_at,
  deleted_at
)
SELECT
  item_type,
  item_id,
  'HAF',
  1,
  'Initial Import',
  '',
  item,
  unixepoch() * 1000,
  unixepoch() * 1000,
  NULL
FROM _haf_primary_weapons
WHERE true
ON CONFLICT(source_key, item_type, item_id, item_version) DO UPDATE SET
  label = excluded.label,
  changelog = excluded.changelog,
  item = excluded.item,
  published_at = unixepoch() * 1000,
  deleted_at = NULL;

DROP TABLE _haf_primary_weapons;

COMMIT;
